name: Notarize repository with cas and vcn

on:
  workflow_call:
    secrets:
      cas-api-key:
        description: 'The signer key for cas.'
        required: true
      vcn-api-key:
        description: 'The signer key for vcn.'
        required: true
      vcn-host:
        description: 'The host for vcn.'
        required: true

jobs:
  notarize-repository:
    name: Notarize repository
    runs-on: [self-hosted, linux]
    env:
      VCN_LC_HOST: ${{ secrets.VCN_LC_HOST }}
      TC_API_KEY: ${{ secrets.TC_API_KEY }}
    steps:
      - name: 'Cleanup build folder'
        run: |
          rm -rf ./* || true
          rm -rf ./.??* || true

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download vcn
        run: |
          curl -s -o vcn -L https://vcn-releases.codenotary.com/vcn-latest-linux-amd64-static
          chmod +x vcn

      - name: Notarize git repository with vcn
        run: ./vcn n git://$GITHUB_WORKSPACE --bom

      - name: Notarize git repository directory with vcn
        run: ./vcn n dir://$GITHUB_WORKSPACE

      - name: Save bom file
        run: ./vcn bom --bom-cdx-json $GITHUB_WORKSPACE.cdx
      
      - name: Notarize via ingest pipeline
        run: >
          curl --fail -X 'POST' \
          'https://$VCN_LC_HOST/dataservice/api/v1/sbom' \
          -H 'accept: application/json' \
          -H 'X-Content-Type: application/vnd.cyclonedx+json' \
          -H 'X-API-KEY: $TC_API_KEY' \
          -H 'Content-Type: application/octet-stream'  \
          --data-binary '@$GITHUB_WORKSPACE.cdx'
          if [ $? -ne 0 ]; then
            echo "Curl command failed"
          fi
          exit 0


