name: 'Notarize repository in Trustcenter'
on:
  workflow_call:
    inputs:
      tc_host:
        description: 'TC host.'
        type: string
        required: true
      tc_api_key:
        description: 'TC API key.'
        type: string
        required: false

jobs:
  notarize-repository:
    name: Notarize repository
    runs-on: [self-hosted, linux]
    steps:
      - name: 'Cleanup build folder'
        run: |
          rm -rf ./* || true
          rm -rf ./.??* || true

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download vcn
        run: |
          curl -s -o vcn -L https://vcn-releases.codenotary.com/vcn-latest-linux-amd64-static
          chmod +x vcn

      - name: Notarize git repository with vcn
        run: ./vcn n git://$GITHUB_WORKSPACE --bom --lc-host ${{inputs.tc_host}} --lc-api-key ${{inputs.tc_api_key}}

      - name: Notarize git repository directory with vcn
        run: ./vcn n dir://$GITHUB_WORKSPACE --lc-host ${{inputs.tc_host}} --lc-api-key ${{inputs.tc_api_key}}

      - name: Save bom file
        run: ./vcn bom git://$GITHUB_WORKSPACE --bom-cdx-json $GITHUB_WORKSPACE.cdx --lc-host ${{inputs.tc_host}} --lc-api-key ${{inputs.tc_api_key}}
      
      - name: Notarize via ingest pipeline
        run: |
          curl --fail -X 'POST' \
          'https://${{inputs.tc_host}}/dataservice/api/v1/sbom' \
          -H 'accept: application/json' \
          -H 'X-Content-Type: application/vnd.cyclonedx+json' \
          -H 'X-API-KEY: ${{inputs.tc_api_key}}' \
          -H 'Content-Type: application/octet-stream'  \
          --data-binary '@$GITHUB_WORKSPACE.cdx' || true
          if [ $? -ne 0 ]; then
            echo "Curl command failed"
          fi
          exit 0


