name: Notarize repository with cas and vcn

on:
  workflow_call:
    secrets:
      cas-api-key:
        description: 'The signer key for cas.'
        required: true
      vcn-api-key:
        description: 'The signer key for vcn.'
        required: true
      vcn-host:
        description: 'The host for vcn.'
        required: true

jobs:
  checkout-repository:
    name: Checkout repository
    runs-on: [self-hosted, linux]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

  notarize-with-cas:
    name: Notarize repository with cas
    runs-on: [self-hosted, linux]
    needs: checkout-repository
    env:
      CAS_HOST: cas.codenotary.com
      CAS_API_KEY: ${{ secrets.cas-api-key }}
    steps:
      - name: Get latest released cas version
        id: cas-version
        run: >
          echo "::set-output name=latest::$(
          curl -s -H 'Accept: application/vnd.github+json'
          -H 'Authorization: token ${{ secrets.GITHUB_TOKEN }}'
          https://api.github.com/repos/codenotary/cas/releases/latest | jq -r '.name'
          )"

      - name: Download cas
        run: |
          curl -s -o cas -L https://github.com/codenotary/cas/releases/download/${{ steps.cas-version.outputs.latest }}/cas-${{ steps.cas-version.outputs.latest }}-linux-amd64-static
          chmod +x cas

      # Notarize only repository as cas cannot notarize the directory
      - name: Notarize git repository with cas
        run: ./cas n git://$GITHUB_WORKSPACE

  notarize-with-vcn:
    name: Notarize repository with vcn
    runs-on: [self-hosted, linux]
    needs: checkout-repository
    env:
      VCN_LC_HOST: ${{ secrets.vcn-host }}
      VCN_LC_API_KEY: ${{ secrets.vcn-api-key }}
    steps:
      - name: Download vcn
        run: |
          curl -s -o vcn -L https://vcn-releases.codenotary.com/vcn-latest-linux-amd64-static
          chmod +x vcn

      - name: Notarize git repository with vcn
        run: ./vcn n git://$GITHUB_WORKSPACE --bom

      - name: Notarize git repository directory with vcn
        run: ./vcn n dir://$GITHUB_WORKSPACE
